name: api_fcm
description: Simple api to send notifications using google FCM endpoint
version: 1.1.0
homepage: https://github.com/lucascardo12/api_fcm

environment:
  sdk: '>=2.17.0 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies: {http: ^0.13.4}
